### ISSUE TITLE
Some questions. 

### ISSUE THREAD

**Issue by zxb16161616** [Joschuka/fmt_g1m#11]
Hello, thank you for the tool! But I'm sorry that I can't find the file "inc_noesis", was it lose?

**Comment by Joschuka** [comment]
Hi, to use this script you need to download Noesis : https://www.richwhitehouse.com/index.php?content=inc_projects.php&showproject=91

The inc_noesis.py file will be in the "plugins\python" folder (this is where you need to put the script too).

**Comment by zxb16161616** [comment]
Thanks for your answer. I realized the problem later~ I just used Ninja ripper to extract the models in OPPW4, but met some problems. I will try your script tomorrow.
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Joschuka/fmt_g1m"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:09
收件人:&nbsp;"Joschuka/fmt_g1m"<fmt_g1m@noreply.github.com&gt;;
抄送:&nbsp;"面试简历书"<424555208@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Joschuka/fmt_g1m] Some questions.  (#11)





 
Hi, to use this script you need to download Noesis : https://www.richwhitehouse.com/index.php?content=inc_projects.php&amp;showproject=91
 
The inc_noesis.py file will be in the "plugins\python" folder (this is where you need to put the script too).
