### ISSUE TITLE
Dissidia Final fantasy Opera Omnia textures

### ISSUE THREAD

**Issue by KekMcGee** [Joschuka/fmt_g1m#2]
Some G1T textures from game do not convert properly. Samples: https://mega.nz/#!8xBkzY4Y!J-ei-b3M-AkWdefbY39kzqijs0mBsFJsYyxARlSti0s comes with both compressed(.dz) and decompressed files.

**Comment by neptuwunium** [comment]
Decompressed files will be supported in the next version

**Comment by Joschuka** [comment]
Should be fixed with b3e47c9
Check out the instructions in the setup section of  the Readme
