### ISSUE TITLE
RuntimeError: Tried to set offset beyond buffer size.

### ISSUE THREAD

**Issue by Andree12** [Joschuka/fmt_g1m#4]
[G2A files.zip](https://github.com/Joschuka/fmt_g1m/files/4117912/G2A.files.zip)

Loading some .G2A animations on models with many bones could not work.
All of the files in the zip came from Fire Emblem Warriors.

**Comment by Joschuka** [comment]
I can confirm that the second animation doesn't work, I'll take a look.

**Comment by Joschuka** [comment]
Could you give me the other g1ms that were in the same folder as that skeleton please ? Got something working but it's hard to see if the result is good with bones only.

**Comment by neptuwunium** [comment]
This is hopefully fixed in the next version.

**Comment by Joschuka** [comment]
Should be fixed with b3e47c9
