### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by WiseHorror** [Joschuka/fmt_g1m#5]
When trying to export a Hyrule Warriors (Wii U) .g1m file, specifically Zelda's LV2 Rapier, I get the error:
`Traceback (most recent call last):
  File "C:\Noesis\plugins\python\fmt_g1m.py", line 1812, in LoadModel
    vertex = mesh.skinWeightList[v]
IndexError: list index out of range`

[Model in question](https://drive.google.com/file/d/1_HIKiy92q1psUwLZcVHy8U1o53lI18Ya/view?usp=sharing)

**Comment by Joschuka** [comment]
I can confirm the issue. It may be related or not to the fact that it's Big Endian.

**Comment by WiseHorror** [comment]
I was able to export the base rapier's model (had to press cancel when it asked for the g1t and anim files, otherwise it would also give an error for the textures).

**Comment by Joschuka** [comment]
Yes we are aware of some texture issues, we will push a few fixes soon !

**Comment by WiseHorror** [comment]
Alright, sweet! Looking forward to it!
Also, Big Endian might not be the only issue, as another person from the BotW Modding Hub discord tried to export the Switch version's LV2 Rapier and they also got an error, although I'm not sure if it was the same error.

**Comment by Joschuka** [comment]
Ah ok I see, other people reported some weight related issues so it can come from that too. I'll keep you updated !

**Comment by Joschuka** [comment]
Should be fixed with b3e47c9
The g1t parser won't crash anymore but the output textures will be swizzled as we don't support WiiU for now. We will probably add it at some point !

**Comment by WiseHorror** [comment]
Thanks! The textures aren't an issue as I can use Switch Toolbox to export them, all I really needed was the model! Keep up the great work!
