### ISSUE TITLE
Meshes not aligned properly with animations in newer versions

### ISSUE THREAD

**Issue by Andree12** [Joschuka/fmt_g1m#6]
Old version:
![old](https://user-images.githubusercontent.com/49048262/73749509-26e11700-4721-11ea-8f4b-2f981f983ad1.png)
Current version:
![new](https://user-images.githubusercontent.com/49048262/73749495-2183cc80-4721-11ea-90de-94e58c474bc1.png)
Can you fix it?

**Comment by Joschuka** [comment]
Can you tell me which update broke it ? I'll take a look this evening.

**Comment by Joschuka** [comment]
Fixed with 4ff795c
